
# RQ3 label audit and meaningful temporal grouping

Run this notebook **before** the final RQ3 / HMM temporal prediction notebook.

Goal:
1. Search the latest usable / ML-ready CSV files in the thesis data folder.
2. Print all label-like columns and their values.
3. Normalize raw labels into a smaller, meaningful Task 3 process vocabulary.
4. Save a cleaned label dataset and mapping table that can be used by the RQ3 HMM notebook.

Important idea:
For temporal prediction, labels should represent meaningful process states, not overly fragmented variants.  
For example, `building_subpiece_together` and `co_building_subpiece` should both map to `building`.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:

# ================================================================
# CELL 1 - SETUP
# ================================================================

import os
import re
import glob
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

# Change this if your thesis folder is elsewhere.
DATA_ROOT = "/content/drive/MyDrive/thesis/data"

OUT_DIR = os.path.join(DATA_ROOT, "RQ3_LABEL_NORMALIZATION")
os.makedirs(OUT_DIR, exist_ok=True)

print("DATA_ROOT:", DATA_ROOT)
print("OUT_DIR:", OUT_DIR)

DATA_ROOT: /content/drive/MyDrive/thesis/data
OUT_DIR: /content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION

In [3]:

# ================================================================
# CELL 2 - FIND CANDIDATE CSV FILES
# ================================================================

FILENAME_KEYWORDS = [
    "ml_ready",
    "ml-ready",
    "activity",
    "advanced",
    "merged",
    "eng3",
    "label_inventory",
    "recognition",
    "interaction",
]

EXCLUDE_KEYWORDS = [
    "summary",
    "prediction",
    "predictions",
    "result",
    "results",
    "best",
    "plot",
    "explain",
    "importance",
    "confusion",
]

all_csvs = sorted(glob.glob(os.path.join(DATA_ROOT, "**", "*.csv"), recursive=True))

candidate_csvs = []
for p in all_csvs:
    name = os.path.basename(p).lower()
    full = p.lower()

    has_good_keyword = any(k in name or k in full for k in FILENAME_KEYWORDS)
    has_bad_keyword = any(k in name or k in full for k in EXCLUDE_KEYWORDS)

    if has_good_keyword and not has_bad_keyword:
        candidate_csvs.append(p)

print("Total CSV files found:", len(all_csvs))
print("Candidate usable/ML-ready CSV files:", len(candidate_csvs))

for i, p in enumerate(candidate_csvs[:250], start=1):
    print(f"{i:03d}. {p}")

Total CSV files found: 1149
Candidate usable/ML-ready CSV files: 155
001. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_ADVANCED_MULTIMODAL_NO_ELAPSED/activity3_multimodal_deep_sequence_aggregate_by_setting.csv
002. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_ADVANCED_MULTIMODAL_NO_ELAPSED/activity3_multimodal_deep_sequence_fold_metrics.csv
003. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_ADVANCED_NO_ELAPSED/activity3_advanced_deep_sequence_aggregate_by_setting.csv
004. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_ADVANCED_NO_ELAPSED/activity3_advanced_deep_sequence_fold_metrics.csv
005. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_NO_ELAPSED/activity3_deep_sequence_no_elapsed_aggregate_by_setting.csv
006. /content/drive/MyDrive/thesis/data/ACTIVITY_3CLASS_DEEP_SEQUENCE_NO_ELAPSED/activity3_deep_sequence_no_elapsed_fold_metrics.csv
007. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/interaction_vs_noninteraction/OE/interaction_vs_noninteraction_OE_dl_no_elapsed_fold_metrics.csv
008. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/interaction_vs_noninteraction/OE_OPTI/interaction_vs_noninteraction_OE_OPTI_dl_no_elapsed_fold_metrics.csv
009. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/interaction_vs_noninteraction/OPTI/interaction_vs_noninteraction_OPTI_dl_no_elapsed_fold_metrics.csv
010. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/interaction_vs_noninteraction/XSENS/interaction_vs_noninteraction_XSENS_dl_no_elapsed_fold_metrics.csv
011. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/interaction_vs_noninteraction/interaction_vs_noninteraction_feature_counts.csv
012. /content/drive/MyDrive/thesis/data/ALL_SENSOR_MULTI_TASK_ABLATIONS/three_class_activity/three_class_activity_feature_counts.csv
013. /content/drive/MyDrive/thesis/data/INTERACTION_ABLATIONS/activity3_advanced_merged_10s_features.csv
014. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_FAST_2models_k200_elapsed_effect.csv
015. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_all_sensor_advanced_features.csv
016. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_base_windows.csv
017. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_oe_advanced_features.csv
018. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_opti2_advanced_features.csv
019. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/binary_5s_xsens2_advanced_features.csv
020. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/label_column_report.csv
021. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_ADVANCED_FEATURES/source_report.csv
022. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY/binary_5s_base_windows_from_model_ready_labels.csv
023. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY/label_column_report.csv
024. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY/source_report.csv
025. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY_FIXED/binary_5s_all_sensor_features.csv
026. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY_FIXED/binary_5s_base_windows_from_model_ready_labels.csv
027. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY_FIXED/label_column_report.csv
028. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_MODEL_READY_FIXED/source_report.csv
029. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/DEEP_SEQUENCE_FINE_TUNING_NO_ELAPSED/fine_tuned_deep_sequence_aggregate_by_setting.csv
030. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/DEEP_SEQUENCE_FINE_TUNING_NO_ELAPSED/fine_tuned_deep_sequence_fold_metrics.csv
031. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/DEEP_SEQUENCE_MODELS_NO_ELAPSED/deep_sequence_no_elapsed_fold_metrics.csv
032. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/DEEP_SEQUENCE_MODELS_NO_ELAPSED/deep_sequence_no_elapsed_selected_features.csv
033. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/binary_5s_specialized_oe9_oe10_features.csv
034. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/binary_5s_specialized_oe_effect.csv
035. /content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/binary_5s_specialized_oe_merged_all_features.csv
036. /content/drive/MyDrive/thesis/data/INTERACTION_ENG/interaction_eng_features.csv
037. /content/drive/MyDrive/thesis/data/INTERACTION_ENG2/interaction_eng_features.csv
038. /content/drive/MyDrive/thesis/data/INTERACTION_ENG2/sensor_ablation_per_group.csv
039. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_binary_label_audit_detailed_labels.csv
040. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_binary_label_audit_windows.csv
041. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_per_group.csv
042. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_3class_core_features.csv
043. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_full_audit.csv
044. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_interaction_only_features.csv
045. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_label_mapping_audit.csv
046. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_raw_label_mapping_audit.csv
047. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/interaction_eng3_features.csv
048. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_classical_folds.csv
049. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_classical_session_time_folds.csv
050. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_classical_session_time_macro_f1_pivot.csv
051. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_classical_simple_time_folds.csv
052. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_classical_simple_time_macro_f1_pivot.csv
053. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_dl_logo_no_validation_folds.csv
054. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_dl_logo_no_validation_vs_classical_comparison.csv
055. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_modality_ablation_folds.csv
056. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_3class_modality_ablation_macro_f1_pivot.csv
057. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_5class_classical_folds.csv
058. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_all_pairwise_wholegroup_raw_label_inventory.csv
059. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
060. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/task3_context_length_transition_only_pivot_all_examples.csv
061. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/task3_context_length_transition_only_pivot_transition_only.csv
062. /content/drive/MyDrive/thesis/data/INTERACTION_ENG3/task3_segment_sequence_deep_models_macro_f1_pivot.csv
063. /content/drive/MyDrive/thesis/data/INTERACTION_ENG4/interaction_eng4_features.csv
064. /content/drive/MyDrive/thesis/data/INTERACTION_ENG5/interaction_eng5_coupling_10s.csv
065. /content/drive/MyDrive/thesis/data/INTERACTION_ENG6/interaction_eng6_5s.csv
066. /content/drive/MyDrive/thesis/data/INTERACTION_ENG7/interaction_eng7_10s.csv
067. /content/drive/MyDrive/thesis/data/INTERACTION_ENG7/interaction_eng7_10s_RAW_GROUP_PAIR_LABELS.csv
068. /content/drive/MyDrive/thesis/data/INTERACTION_ENG7_CONTEXT/interaction_eng7_context_5s.csv
069. /content/drive/MyDrive/thesis/data/INTERACTION_ENG_30S/interaction_eng30_features.csv
070. /content/drive/MyDrive/thesis/data/INTERACTION_OE10/final_feature_lists/combined_final_feature_lists.csv
071. /content/drive/MyDrive/thesis/data/INTERACTION_OE10/interaction_oe10_10s.csv
072. /content/drive/MyDrive/thesis/data/INTERACTION_OE8/interaction_oe8_10s.csv
073. /content/drive/MyDrive/thesis/data/INTERACTION_OE9/interaction_oe9_10s.csv
074. /content/drive/MyDrive/thesis/data/INTERACTION_OPTI2/interaction_opti2_10s.csv
075. /content/drive/MyDrive/thesis/data/INTERACTION_OPTI2/opti2_source_selection_report.csv
076. /content/drive/MyDrive/thesis/data/INTERACTION_WINDOWS/interaction_fixed_features.csv
077. /content/drive/MyDrive/thesis/data/INTERACTION_WINDOWS/interaction_labeled_features.csv
078. /content/drive/MyDrive/thesis/data/INTERACTION_XSENS2/interaction_xsens2_10s.csv
079. /content/drive/MyDrive/thesis/data/INTERACTION_XSENS2/xsens2_source_selection_report.csv
080. /content/drive/MyDrive/thesis/data/ML_DATASETS/fused_multimodal_activity_token_report.csv
081. /content/drive/MyDrive/thesis/data/ML_DATASETS/fused_multimodal_activity_tokens.csv
082. /content/drive/MyDrive/thesis/data/ML_DATASETS/fused_multimodal_activity_tokens_clean_min0p5.csv
083. /content/drive/MyDrive/thesis/data/ML_DATASETS/model1_interaction_binary_tokens.csv
084. /content/drive/MyDrive/thesis/data/ML_DATASETS/model1_scene_interaction_token_report.csv
085. /content/drive/MyDrive/thesis/data/ML_DATASETS/model1_scene_interaction_tokens.csv
086. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2B_scene_group_activity_3class_report.csv
087. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2B_scene_group_activity_3class_tokens.csv
088. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2_group_activity_5class_mapping.csv
089. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2_group_activity_5class_tokens.csv
090. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2_scene_group_activity_5class_report.csv
091. /content/drive/MyDrive/thesis/data/ML_DATASETS/model2_scene_group_activity_5class_tokens.csv
092. /content/drive/MyDrive/thesis/data/ML_DATASETS/model3_masked_activity_3class_tokens.csv
093. /content/drive/MyDrive/thesis/data/ML_DATASETS/model3_masked_activity_5class_tokens.csv
094. /content/drive/MyDrive/thesis/data/ML_DATASETS/model3_next_activity_3class_tokens.csv
095. /content/drive/MyDrive/thesis/data/ML_DATASETS/model3_next_activity_5class_tokens.csv
096. /content/drive/MyDrive/thesis/data/ML_MODELS/model1_interaction_transformer/training_history.csv
097. /content/drive/MyDrive/thesis/data/ML_MODELS/model1_interaction_transformer_v2/training_history.csv
098. /content/drive/MyDrive/thesis/data/ML_MODELS/model1_interaction_transformer_v3_threshold_tuned/training_history.csv
099. /content/drive/MyDrive/thesis/data/ML_MODELS/model1_scene_interaction_transformer/training_history.csv
100. /content/drive/MyDrive/thesis/data/ML_MODELS/model1_scene_interaction_transformer_no_leakage/training_history.csv
101. /content/drive/MyDrive/thesis/data/RECOGNITION_5CLASS/recognition_fixed_features_5class.csv
102. /content/drive/MyDrive/thesis/data/RECOGNITION_ENG2/recognition_fixed_features.csv
103. /content/drive/MyDrive/thesis/data/RECOGNITION_ENG2/recognition_labeled_features.csv
104. /content/drive/MyDrive/thesis/data/RECOGNITION_WINDOWS/recognition_fixed_features.csv
105. /content/drive/MyDrive/thesis/data/RECOGNITION_WINDOWS/recognition_labeled_features.csv
106. /content/drive/MyDrive/thesis/data/group_1/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
107. /content/drive/MyDrive/thesis/data/group_1/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
108. /content/drive/MyDrive/thesis/data/group_1/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
109. /content/drive/MyDrive/thesis/data/group_1/openearable/openearable_labeled/openearable_merged/group_1_openearable_merged_50hz.csv
110. /content/drive/MyDrive/thesis/data/group_1/xsens/xsens_labeled/xsense_initial/xsens_merged/group_1_xsens_merged_30hz.csv
111. /content/drive/MyDrive/thesis/data/group_10/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
112. /content/drive/MyDrive/thesis/data/group_10/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
113. /content/drive/MyDrive/thesis/data/group_10/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
114. /content/drive/MyDrive/thesis/data/group_10/openearable/openearable_labeled/openearable_merged/group_10_openearable_merged_50hz.csv
115. /content/drive/MyDrive/thesis/data/group_10/xsens/xsens_labeled/xsens_merged/group_10_xsens_merged_30hz.csv
116. /content/drive/MyDrive/thesis/data/group_10/xsens/xsens_labeled/xsens_merged/group_10_xsens_merged_30hz_CONTINUOUS.csv
117. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
118. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
119. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
120. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/openearable_merged/group_2_openearable_merged_50hz.csv
121. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/processed_openearable/group_2_openearable_p1_merged.csv
122. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/processed_openearable/group_2_openearable_p2_merged.csv
123. /content/drive/MyDrive/thesis/data/group_2/openearable/openearable_labeled/processed_openearable/group_2_openearable_p3_merged.csv
124. /content/drive/MyDrive/thesis/data/group_2/xsens/xsens_labeled/xsens_merged/group_2_xsens_merged_30hz.csv
125. /content/drive/MyDrive/thesis/data/group_3/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
126. /content/drive/MyDrive/thesis/data/group_3/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
127. /content/drive/MyDrive/thesis/data/group_3/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
128. /content/drive/MyDrive/thesis/data/group_3/openearable/openearable_labeled/openearable_merged/group_3_openearable_merged_50hz.csv
129. /content/drive/MyDrive/thesis/data/group_3/xsens/xsens_labeled/xsens_merged/group_3_xsens_merged_30hz.csv
130. /content/drive/MyDrive/thesis/data/group_5/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
131. /content/drive/MyDrive/thesis/data/group_5/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
132. /content/drive/MyDrive/thesis/data/group_5/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
133. /content/drive/MyDrive/thesis/data/group_5/openearable/openearable_labeled/openearable_merged/group_5_openearable_merged_50hz.csv
134. /content/drive/MyDrive/thesis/data/group_5/xsens/xsens_labeled/xsens_merged/group_5_xsens_merged_30hz.csv
135. /content/drive/MyDrive/thesis/data/group_6/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
136. /content/drive/MyDrive/thesis/data/group_6/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
137. /content/drive/MyDrive/thesis/data/group_6/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
138. /content/drive/MyDrive/thesis/data/group_6/openearable/openearable_labeled/openearable_merged/group_6_openearable_merged_50hz.csv
139. /content/drive/MyDrive/thesis/data/group_6/xsens/xsens_labeled/xsens_merged/group_6_xsens_merged_30hz.csv
140. /content/drive/MyDrive/thesis/data/group_7/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
141. /content/drive/MyDrive/thesis/data/group_7/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
142. /content/drive/MyDrive/thesis/data/group_7/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
143. /content/drive/MyDrive/thesis/data/group_7/openearable/openearable_labeled/openearable_merged/group_7_openearable_merged_50hz.csv
144. /content/drive/MyDrive/thesis/data/group_7/xsens/xsens_labeled/xsens_merged/group_7_xsens_merged_30hz_UPDATED_ALL3.csv
145. /content/drive/MyDrive/thesis/data/group_8/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
146. /content/drive/MyDrive/thesis/data/group_8/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
147. /content/drive/MyDrive/thesis/data/group_8/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
148. /content/drive/MyDrive/thesis/data/group_8/openearable/openearable_labeled/openearable_merged/group_8_openearable_merged_50hz.csv
149. /content/drive/MyDrive/thesis/data/group_8/xsens/xsens_labeled/xsens_merged/group_8_xsens_merged_30hz.csv
150. /content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/Participant1_openearable_merged_50hz.csv
151. /content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/Participant2_openearable_merged_50hz.csv
152. /content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/Participant3_openearable_merged_50hz.csv
153. /content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/group_9_openearable_merged_50hz.csv
154. /content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz.csv
155. /content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz_CONTINUOUS.csv

In [4]:

# ================================================================
# CELL 3 - DETECT LABEL-LIKE COLUMNS IN CANDIDATE FILES
# ================================================================

LABEL_KEYWORDS = [
    "label",
    "activity",
    "state",
    "target",
    "class",
    "dominant",
    "normalized",
    "recognition",
]

def looks_like_label_column(col):
    c = str(col).lower()
    if any(k in c for k in LABEL_KEYWORDS):
        bad = ["prob", "score", "confidence", "duration", "count", "n_", "num_", "ratio"]
        if not any(b in c for b in bad):
            return True
    return False


label_column_rows = []

for path in candidate_csvs:
    try:
        sample = pd.read_csv(path, nrows=100)
    except Exception as e:
        print("Could not read:", path, "|", repr(e))
        continue

    label_cols = [c for c in sample.columns if looks_like_label_column(c)]

    if len(label_cols) == 0:
        continue

    try:
        n_rows = sum(1 for _ in open(path, "rb")) - 1
    except Exception:
        n_rows = np.nan

    for c in label_cols:
        vals = sample[c].dropna().astype(str)
        vals = vals[vals.str.strip() != ""]
        label_column_rows.append({
            "file_path": path,
            "file_name": os.path.basename(path),
            "n_rows_estimate": n_rows,
            "label_column": c,
            "sample_n_unique": vals.nunique(),
            "sample_values": " | ".join(vals.value_counts().head(10).index.tolist()),
        })

label_columns_df = pd.DataFrame(label_column_rows)

if len(label_columns_df) == 0:
    raise RuntimeError("No label-like columns found in candidate CSVs. Try loosening FILENAME_KEYWORDS or LABEL_KEYWORDS.")

label_columns_df = label_columns_df.sort_values(
    ["file_name", "label_column"]
).reset_index(drop=True)

print("Detected label-like columns:")
display(label_columns_df)

label_columns_df.to_csv(
    os.path.join(OUT_DIR, "detected_label_columns_in_candidate_files.csv"),
    index=False
)

print("Saved:", os.path.join(OUT_DIR, "detected_label_columns_in_candidate_files.csv"))

Detected label-like columns:

,file_path,file_name,n_rows_estimate,label_column,sample_n_unique,sample_values
0,/content/drive/MyDrive/thesis/data/INTERACTION...,binary_5s_all_sensor_advanced_features.csv,4579,binary_label,2,non_interaction | interaction
1,/content/drive/MyDrive/thesis/data/INTERACTION...,binary_5s_all_sensor_advanced_features.csv,4579,label_source_path,1,/content/drive/MyDrive/thesis/data/ALL_MODEL_R...
2,/content/drive/MyDrive/thesis/data/INTERACTION...,binary_5s_all_sensor_advanced_features.csv,4579,label_source_sensor,1,OE
3,/content/drive/MyDrive/thesis/data/INTERACTION...,binary_5s_all_sensor_features.csv,4579,binary_label,2,non_interaction | interaction
4,/content/drive/MyDrive/thesis/data/INTERACTION...,binary_5s_all_sensor_features.csv,4579,label_source_path,1,/content/drive/MyDrive/thesis/data/ALL_MODEL_R...
...,...,...,...,...,...,...
235,/content/drive/MyDrive/thesis/data/INTERACTION...,recognition_interaction_window_label_inventory...,2080,dominant_normalized_label,11,task_operational_convo | task_social_convo | t...
236,/content/drive/MyDrive/thesis/data/INTERACTION...,recognition_interaction_window_label_inventory...,2080,dominant_raw_label,11,task_operational_convo | task_social_convo | t...
237,/content/drive/MyDrive/thesis/data/RECOGNITION...,recognition_labeled_features.csv,112,label,3,conversation | co_building | co_merging
238,/content/drive/MyDrive/thesis/data/RECOGNITION...,recognition_labeled_features.csv,155,label,6,conversation | co_building | co_merging | othe...
239,/content/drive/MyDrive/thesis/data/INTERACTION...,task3_segment_sequence_deep_models_macro_f1_pi...,6,markov_current_activity,3,0.1104701030226433 | 0.1020201153058125 | 0.09...

Saved: /content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/detected_label_columns_in_candidate_files.csv

In [5]:

# ================================================================
# CELL 4 - FULL LABEL INVENTORY ACROSS DETECTED FILES
# ================================================================

inventory_rows = []

for _, row in label_columns_df.iterrows():
    path = row["file_path"]
    col = row["label_column"]

    try:
        df_tmp = pd.read_csv(path, usecols=[col])
    except Exception as e:
        print("Could not read column:", col, "from", path, "|", repr(e))
        continue

    vals = df_tmp[col].dropna().astype(str).str.strip()
    vals = vals[vals != ""]

    vc = vals.value_counts(dropna=False)

    for label, count in vc.items():
        inventory_rows.append({
            "file_path": path,
            "file_name": os.path.basename(path),
            "label_column": col,
            "raw_label": label,
            "count": int(count),
        })

label_inventory = pd.DataFrame(inventory_rows)

label_inventory = label_inventory.sort_values(
    ["file_name", "label_column", "count"],
    ascending=[True, True, False]
).reset_index(drop=True)

print("Combined label inventory:")
display(label_inventory)

out_path = os.path.join(OUT_DIR, "all_detected_raw_labels_inventory.csv")
label_inventory.to_csv(out_path, index=False)

print("Saved:", out_path)

Combined label inventory:

                                               file_path                                          file_name             label_column                                          raw_label  count
0      /content/drive/MyDrive/thesis/data/INTERACTION...         binary_5s_all_sensor_advanced_features.csv             binary_label                                    non_interaction   2304
1      /content/drive/MyDrive/thesis/data/INTERACTION...         binary_5s_all_sensor_advanced_features.csv             binary_label                                        interaction   2275
2      /content/drive/MyDrive/thesis/data/INTERACTION...         binary_5s_all_sensor_advanced_features.csv        label_source_path  /content/drive/MyDrive/thesis/data/ALL_MODEL_R...    792
3      /content/drive/MyDrive/thesis/data/INTERACTION...         binary_5s_all_sensor_advanced_features.csv        label_source_path  /content/drive/MyDrive/thesis/data/ALL_MODEL_R...    713
4      /content/drive/MyDrive/thesis/data/INTERACTION...         binary_5s_all_sensor_advanced_features.csv        label_source_path  /content/drive/MyDrive/thesis/data/ALL_MODEL_R...    579
...                                                  ...                                                ...                      ...                                                ...    ...
23315  /content/drive/MyDrive/thesis/data/RECOGNITION...                   recognition_labeled_features.csv                    label                                              other      6
23316  /content/drive/MyDrive/thesis/data/RECOGNITION...                   recognition_labeled_features.csv                    label                                  material_handling      2
23317  /content/drive/MyDrive/thesis/data/INTERACTION...  task3_segment_sequence_deep_models_macro_f1_pi...  markov_current_activity                                 0.1104701030226433      2
23318  /content/drive/MyDrive/thesis/data/INTERACTION...  task3_segment_sequence_deep_models_macro_f1_pi...  markov_current_activity                                 0.1020201153058125      2
23319  /content/drive/MyDrive/thesis/data/INTERACTION...  task3_segment_sequence_deep_models_macro_f1_pi...  markov_current_activity                                 0.0970821703087149      2

[23320 rows x 5 columns]

Saved: /content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/all_detected_raw_labels_inventory.csv

In [6]:

# ================================================================
# CELL 5 - CHOOSE MAIN LABEL FILE / COLUMN
# ================================================================

preferred_candidates = []

for _, row in label_columns_df.iterrows():
    p = row["file_path"]
    c = row["label_column"]
    plow = p.lower()
    clow = c.lower()

    score = 0

    if "recognition_interaction_window_label_inventory" in plow:
        score += 100
    if "activity3_advanced_merged_10s_features" in plow:
        score += 80
    if "ml_ready" in plow or "ml-ready" in plow:
        score += 60
    if "merged" in plow:
        score += 20
    if "dominant_normalized_label" == clow:
        score += 50
    if "activity" in clow:
        score += 30
    if "target" in clow:
        score += 10

    preferred_candidates.append((score, p, c))

preferred_candidates = sorted(preferred_candidates, reverse=True)

print("Top candidate label sources:")
for score, p, c in preferred_candidates[:30]:
    print(f"score={score:03d} | col={c} | file={p}")

MAIN_FILE = preferred_candidates[0][1]
MAIN_LABEL_COL = preferred_candidates[0][2]

# OPTIONAL MANUAL OVERRIDE:
# MAIN_FILE = "/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv"
# MAIN_LABEL_COL = "dominant_normalized_label"

print("\nSelected MAIN_FILE:")
print(MAIN_FILE)
print("Selected MAIN_LABEL_COL:")
print(MAIN_LABEL_COL)

main_df = pd.read_csv(MAIN_FILE)

print("\nMain file shape:", main_df.shape)
print("Main file columns:")
print(main_df.columns.tolist())

if MAIN_LABEL_COL not in main_df.columns:
    raise ValueError(f"{MAIN_LABEL_COL} not found in MAIN_FILE.")

print("\nRaw label distribution in selected source:")
display(main_df[MAIN_LABEL_COL].astype(str).value_counts().reset_index().rename(
    columns={"index": "raw_label", MAIN_LABEL_COL: "count"}
))

Top candidate label sources:
score=150 | col=dominant_normalized_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
score=100 | col=dominant_raw_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
score=100 | col=dominant_is_technical_or_sync | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
score=100 | col=binary_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
score=050 | col=dominant_normalized_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_label_mapping_audit.csv
score=050 | col=dominant_normalized_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_interaction_only_features.csv
score=050 | col=dominant_normalized_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_5class_full_audit.csv
score=050 | col=dominant_normalized_label | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/eng3_recognition_3class_core_features.csv
score=050 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/binary_5s_specialized_oe_merged_all_features.csv
score=030 | col=group_activity_class_id | file=/content/drive/MyDrive/thesis/data/ML_DATASETS/model2_group_activity_5class_tokens.csv
score=030 | col=other_group_activity | file=/content/drive/MyDrive/thesis/data/ML_DATASETS/model2B_scene_group_activity_3class_report.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_OE9/interaction_oe9_10s.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_OE8/interaction_oe8_10s.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_OE10/interaction_oe10_10s.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG7_CONTEXT/interaction_eng7_context_5s.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG7/interaction_eng7_10s_RAW_GROUP_PAIR_LABELS.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG7/interaction_eng7_10s.csv
score=030 | col=markov_current_activity | file=/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/task3_segment_sequence_deep_models_macro_f1_pivot.csv
score=030 | col=ear_head_activity_alternation | file=/content/drive/MyDrive/thesis/data/INTERACTION_BINARY_5S_SPECIALIZED_OE/binary_5s_specialized_oe9_oe10_features.csv
score=020 | col=label_p3 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz_CONTINUOUS.csv
score=020 | col=label_p2 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz_CONTINUOUS.csv
score=020 | col=label_p1 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz_CONTINUOUS.csv
score=020 | col=label_p3 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz.csv
score=020 | col=label_p2 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz.csv
score=020 | col=label_p1 | file=/content/drive/MyDrive/thesis/data/group_9/xsens/xsens_labeled/xsens_merged/group_9_xsens_merged_30hz.csv
score=020 | col=label_p3 | file=/content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/group_9_openearable_merged_50hz.csv
score=020 | col=label_p2 | file=/content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/group_9_openearable_merged_50hz.csv
score=020 | col=label_p1 | file=/content/drive/MyDrive/thesis/data/group_9/openearable/openearable_labeled/openearable_merged/group_9_openearable_merged_50hz.csv
score=020 | col=label_p3 | file=/content/drive/MyDrive/thesis/data/group_8/xsens/xsens_labeled/xsens_merged/group_8_xsens_merged_30hz.csv
score=020 | col=label_p2 | file=/content/drive/MyDrive/thesis/data/group_8/xsens/xsens_labeled/xsens_merged/group_8_xsens_merged_30hz.csv

Selected MAIN_FILE:
/content/drive/MyDrive/thesis/data/INTERACTION_ENG3/recognition_interaction_window_label_inventory.csv
Selected MAIN_LABEL_COL:
dominant_normalized_label

Main file shape: (2080, 11)
Main file columns:
['group', 'window_start', 'window_end', 'binary_label', 'dominant_raw_label', 'dominant_normalized_label', 'dominant_is_technical_or_sync', 'dominant_fraction_in_window', 'all_raw_labels_in_window', 'source_tiers_in_window', 'raw_label_counts']

Raw label distribution in selected source:

                                                count  count
0                                co_building_subpiece    999
1                              task_operational_convo    350
2                                    merging_subpiece    176
3                                   task_social_convo    113
4                                 co_merging_subpiece     81
5                               moving_pieces_to_tray     45
6                            co_moving_pieces_to_tray     38
7                                   inspecting_pieces     29
8                                     object_handover     24
9                                co_inspecting_pieces     23
10                         building_subpiece_together     18
11                                  co_building_piece     15
12           object_handover_+_task_operational_convo     12
13                                 task_related_convo      9
14        inspecting_target_image_+_inspecting_pieces      9
15                            inspecting_target_image      8
16                                     non_task_convo      7
17                        co_placing_subpiece_to_tray      7
18                          task_related_social_convo      6
19      co_building_subpiece_+_task_operational_convo      6
20                                      co_inspecting      6
21                           placing_subpiece_to_tray      5
22                           inspecting_puzzle_pieces      5
23                                searching_for_piece      5
24          task_operational_convo_+_inspecting_setup      5
25           moving_pieces_from_tray_to_central_table      5
26                   moving_pieces_from_table_to_tray      5
27      task_operational_convo_+_co_inspecting_pieces      5
28  co_inspecting_target_image_+_task_operational_...      4
29                                   inspecting_piece      4
30      co_inspecting_pieces_+_task_operational_convo      4
31    task_operational_convo_+_co_searching_for_piece      4
32                                co_inspecting_image      3
33                         co_inspecting_target_image      3
34                                   inspecting_setup      3
35                            delivering_target_image      3
36                                inspecting_subpiece      3
37        inspecting_pieces_+_inspecting_target_image      3
38                               synchronization_move      3
39                                   delivering_piece      2
40         inspecting_pieces_+_task_operational_convo      2
41  task_operational_convo_+_moving_pieces_from_ta...      2
42  inspecting_target_image_+_matching_pieces_to_t...      2
43       task_operational_convo_+_inspecting_subpiece      2
44  co_moving_pieces_from_tray_to_central_table_+_...      2
45                         co_traveling_between_units      2
46   inspecting_target_image_+_task_operational_convo      1
47                        approaching_to_single_units      1
48                            traveling_between_units      1
49                    matching_pieces_to_target_image      1
50              object_handover_+_co_inspecting_image      1
51                  co_carrying_tray_to_central_table      1
52  approaching_to_central_table_+_task_operationa...      1
53  co_traveling_between_units_+_task_operational_...      1
54                                   co_carrying_tray      1
55                                co_inspecting_piece      1
56                          starting_individual_build      1
57                             co_inspecting_subpiece      1
58           object_handiver_+_task_operational_convo      1

In [7]:

# ================================================================
# CELL 6 - NORMALIZATION FUNCTIONS
# ================================================================

def clean_label(x):
    if pd.isna(x):
        return "none"

    s = str(x).strip().lower()
    s = s.replace("-", "_").replace(" ", "_")
    s = re.sub(r"__+", "_", s)
    s = s.strip("_")

    replacements = {
        "object_handiver": "object_handover",
        "matching_pieces_with_target_image": "matching_pieces_to_target_image",
        "matching_pieces_to_image": "matching_pieces_to_target_image",
        "matching_pieces_with_image": "matching_pieces_to_target_image",
        "non_task_convo": "task_social_convo",
        "task_related_social_convo": "task_social_convo",
        "task_related_convo": "task_operational_convo",
    }

    for old, new in replacements.items():
        s = s.replace(old, new)

    return s


def split_compound_label(x):
    # Splits labels such as task_operational_convo_+_co_inspecting_pieces.
    s = clean_label(x)
    parts = re.split(r"_\+_|\+|,|;", s)
    parts = [p.strip("_ ").strip() for p in parts if p.strip("_ ").strip()]
    if len(parts) == 0:
        parts = ["none"]
    return parts


def component_to_process_label(component):
    # Meaningful Task 3 process grouping.
    # Individual and co versions of the same process are intentionally merged.
    c = clean_label(component)

    if c in ["none", "nan", ""]:
        return "other"

    if "convo" in c or "conversation" in c:
        if "social" in c or "non_task" in c:
            return "social_conversation"
        return "task_conversation"

    if "handover" in c or "delivering_piece" in c or "delivering_target_image" in c:
        return "object_handover"

    if (
        "building" in c
        or "build" in c
        or "subpiece_together" in c
        or "placing_subpiece" in c
        or "placing_piece" in c
        or "starting_individual_build" in c
    ):
        return "building"

    if "merging" in c or "merge" in c:
        return "merging"

    if (
        "inspect" in c
        or "inspection" in c
        or "matching" in c
        or "searching" in c
        or "target_image" in c
        or "puzzle_pieces" in c
    ):
        return "inspection"

    if (
        "moving" in c
        or "tray" in c
        or "carrying" in c
        or "traveling" in c
        or "approaching" in c
        or "move" in c
        or "transport" in c
    ):
        return "moving_transport"

    if "synchronization" in c or "sync" in c:
        return "moving_transport"

    return "other"


# Priority for compound labels.
# Example: task_operational_convo + co_inspecting_pieces.
# For temporal process prediction, we prioritize the physical task process if it is present.
PROCESS_PRIORITY = [
    "merging",
    "building",
    "moving_transport",
    "inspection",
    "object_handover",
    "task_conversation",
    "social_conversation",
    "other",
]


def raw_to_process_label(raw_label):
    parts = split_compound_label(raw_label)
    mapped = [component_to_process_label(p) for p in parts]

    for p in PROCESS_PRIORITY:
        if p in mapped:
            return p

    return "other"


def raw_to_conversation_binary(raw_label):
    parts = split_compound_label(raw_label)
    mapped = [component_to_process_label(p) for p in parts]
    return "conversation" if ("task_conversation" in mapped or "social_conversation" in mapped) else "non_conversation"


def raw_to_compact_process_label(raw_label):
    p = raw_to_process_label(raw_label)

    if p in ["task_conversation", "social_conversation"]:
        return "conversation"
    if p == "building":
        return "building"
    if p == "merging":
        return "merging"
    if p in ["inspection", "moving_transport", "object_handover"]:
        return "preparation_or_transition"
    return "other"


print("Normalization functions loaded.")

Normalization functions loaded.

In [8]:

# ================================================================
# CELL 7 - APPLY NORMALIZATION AND PRINT RAW -> GROUPED MAPPING
# ================================================================

df = main_df.copy()

df["raw_label"] = df[MAIN_LABEL_COL].astype(str).map(clean_label)
df["rq3_process_label"] = df["raw_label"].map(raw_to_process_label)
df["rq3_compact_process_label"] = df["raw_label"].map(raw_to_compact_process_label)
df["rq3_conversation_binary"] = df["raw_label"].map(raw_to_conversation_binary)

mapping_table = (
    df
    .groupby(["raw_label", "rq3_process_label", "rq3_compact_process_label", "rq3_conversation_binary"], as_index=False)
    .size()
    .rename(columns={"size": "count"})
    .sort_values(["rq3_process_label", "count"], ascending=[True, False])
)

print("=" * 100)
print("RAW LABEL -> NORMALIZED TASK 3 LABEL MAPPING")
print("=" * 100)
display(mapping_table)

print("\nDistribution: rq3_process_label")
display(df["rq3_process_label"].value_counts().reset_index().rename(
    columns={"index": "rq3_process_label", "rq3_process_label": "count"}
))

print("\nDistribution: rq3_compact_process_label")
display(df["rq3_compact_process_label"].value_counts().reset_index().rename(
    columns={"index": "rq3_compact_process_label", "rq3_compact_process_label": "count"}
))

print("\nDistribution: rq3_conversation_binary")
display(df["rq3_conversation_binary"].value_counts().reset_index().rename(
    columns={"index": "rq3_conversation_binary", "rq3_conversation_binary": "count"}
))

mapping_path = os.path.join(OUT_DIR, "rq3_raw_to_normalized_label_mapping.csv")
mapping_table.to_csv(mapping_path, index=False)

print("\nSaved mapping:", mapping_path)

====================================================================================================
RAW LABEL -> NORMALIZED TASK 3 LABEL MAPPING
====================================================================================================

                                            raw_label    rq3_process_label  rq3_compact_process_label rq3_conversation_binary  count
4                                co_building_subpiece             building                   building        non_conversation    999
2                          building_subpiece_together             building                   building        non_conversation     18
3                                   co_building_piece             building                   building        non_conversation     15
19                        co_placing_subpiece_to_tray             building                   building        non_conversation      7
5       co_building_subpiece_+_task_operational_convo             building                   building            conversation      6
43                           placing_subpiece_to_tray             building                   building        non_conversation      5
45                          starting_individual_build             building                   building        non_conversation      1
25                                  inspecting_pieces           inspection  preparation_or_transition        non_conversation     29
11                               co_inspecting_pieces           inspection  preparation_or_transition        non_conversation     23
32        inspecting_target_image_+_inspecting_pieces           inspection  preparation_or_transition        non_conversation      9
31                            inspecting_target_image           inspection  preparation_or_transition        non_conversation      8
8                                       co_inspecting           inspection  preparation_or_transition        non_conversation      6
28                           inspecting_puzzle_pieces           inspection  preparation_or_transition        non_conversation      5
44                                searching_for_piece           inspection  preparation_or_transition        non_conversation      5
48      task_operational_convo_+_co_inspecting_pieces           inspection  preparation_or_transition            conversation      5
50          task_operational_convo_+_inspecting_setup           inspection  preparation_or_transition            conversation      5
12      co_inspecting_pieces_+_task_operational_convo           inspection  preparation_or_transition            conversation      4
15  co_inspecting_target_image_+_task_operational_...           inspection  preparation_or_transition            conversation      4
24                                   inspecting_piece           inspection  preparation_or_transition        non_conversation      4
49    task_operational_convo_+_co_searching_for_piece           inspection  preparation_or_transition            conversation      4
9                                 co_inspecting_image           inspection  preparation_or_transition        non_conversation      3
14                         co_inspecting_target_image           inspection  preparation_or_transition        non_conversation      3
26        inspecting_pieces_+_inspecting_target_image           inspection  preparation_or_transition        non_conversation      3
29                                   inspecting_setup           inspection  preparation_or_transition        non_conversation      3
30                                inspecting_subpiece           inspection  preparation_or_transition        non_conversation      3
27         inspecting_pieces_+_task_operational_convo           inspection  preparation_or_transition            conversation      2
33  inspecting_target_image_+_matching_pieces_to_t...           inspection  preparation_or_transition        non_conversation      2
51       task_operational_convo_+_inspecting_subpiece           inspection  preparation_or_transition            conversation      2
10                                co_inspecting_piece           inspection  preparation_or_transition        non_conversation      1
13                             co_inspecting_subpiece           inspection  preparation_or_transition        non_conversation      1
34   inspecting_target_image_+_task_operational_convo           inspection  preparation_or_transition            conversation      1
35                    matching_pieces_to_target_image           inspection  preparation_or_transition        non_conversation      1
41              object_handover_+_co_inspecting_image           inspection  preparation_or_transition        non_conversation      1
36                                   merging_subpiece              merging                    merging        non_conversation    176
16                                co_merging_subpiece              merging                    merging        non_conversation     81
17  co_moving_pieces_from_tray_to_central_table_+_...              merging                    merging        non_conversation      2
39                              moving_pieces_to_tray     moving_transport  preparation_or_transition        non_conversation     45
18                           co_moving_pieces_to_tray     moving_transport  preparation_or_transition        non_conversation     38
37                   moving_pieces_from_table_to_tray     moving_transport  preparation_or_transition        non_conversation      5
38           moving_pieces_from_tray_to_central_table     moving_transport  preparation_or_transition        non_conversation      5
46                               synchronization_move     moving_transport  preparation_or_transition        non_conversation      3
20                         co_traveling_between_units     moving_transport  preparation_or_transition        non_conversation      2
52  task_operational_convo_+_moving_pieces_from_ta...     moving_transport  preparation_or_transition            conversation      2
0   approaching_to_central_table_+_task_operationa...     moving_transport  preparation_or_transition            conversation      1
1                         approaching_to_single_units     moving_transport  preparation_or_transition        non_conversation      1
6                                    co_carrying_tray     moving_transport  preparation_or_transition        non_conversation      1
7                   co_carrying_tray_to_central_table     moving_transport  preparation_or_transition        non_conversation      1
21  co_traveling_between_units_+_task_operational_...     moving_transport  preparation_or_transition            conversation      1
54                            traveling_between_units     moving_transport  preparation_or_transition        non_conversation      1
40                                    object_handover      object_handover  preparation_or_transition        non_conversation     24
42           object_handover_+_task_operational_convo      object_handover  preparation_or_transition            conversation     13
23                            delivering_target_image      object_handover  preparation_or_transition        non_conversation      3
22                                   delivering_piece      object_handover  preparation_or_transition        non_conversation      2
53                                  task_social_convo  social_conversation               conversation            conversation    126
47                             task_operational_convo    task_conversation               conversation            conversation    359

Distribution: rq3_process_label

                 count  count
0             building   1051
1    task_conversation    359
2              merging    259
3           inspection    137
4  social_conversation    126
5     moving_transport    106
6      object_handover     42

Distribution: rq3_compact_process_label

                       count  count
0                   building   1051
1               conversation    485
2  preparation_or_transition    285
3                    merging    259

Distribution: rq3_conversation_binary

              count  count
0  non_conversation   1545
1      conversation    535

Saved mapping: /content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/rq3_raw_to_normalized_label_mapping.csv

In [9]:

# ================================================================
# CELL 8 - CHECK TEMPORAL SEQUENCES AND TRANSITIONS
# ================================================================

def find_first_existing(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

GROUP_COL = find_first_existing(df.columns, ["group", "group_id", "session", "session_id", "participant_group"])
TIME_COL = find_first_existing(df.columns, ["window_start", "win_start", "start", "start_time", "timestamp", "time", "window_mid"])

print("Detected GROUP_COL:", GROUP_COL)
print("Detected TIME_COL:", TIME_COL)

# Manual override if needed:
# GROUP_COL = "group"
# TIME_COL = "window_start"

if GROUP_COL is None or TIME_COL is None:
    print("Could not detect group/time columns automatically.")
    print("Available columns:")
    print(df.columns.tolist())
else:
    temp = df.copy()
    temp[TIME_COL] = pd.to_numeric(temp[TIME_COL], errors="coerce")
    temp = temp.sort_values([GROUP_COL, TIME_COL])

    def collapse_repeats(seq):
        out = []
        for x in seq:
            if len(out) == 0 or out[-1] != x:
                out.append(x)
        return out

    for label_col in ["rq3_process_label", "rq3_compact_process_label"]:
        print("\n" + "=" * 100)
        print("SEGMENT SEQUENCES FOR:", label_col)
        print("=" * 100)

        seg_counts = []
        transition_rows = []

        for g, sub in temp.groupby(GROUP_COL):
            seq_win = sub[label_col].astype(str).tolist()
            seq_seg = collapse_repeats(seq_win)
            seg_counts.append(len(seq_seg))

            print(f"group {g}: {len(seq_win)} windows -> {len(seq_seg)} segments")
            print("  " + " -> ".join(seq_seg[:90]))

            for a, b in zip(seq_seg[:-1], seq_seg[1:]):
                transition_rows.append({
                    "label_col": label_col,
                    "group": g,
                    "from": a,
                    "to": b,
                })

        print("\nSegment count summary:")
        print(pd.Series(seg_counts).describe())

        trans_df = pd.DataFrame(transition_rows)
        if len(trans_df) > 0:
            trans_counts = (
                trans_df
                .groupby(["from", "to"], as_index=False)
                .size()
                .rename(columns={"size": "count"})
                .sort_values("count", ascending=False)
            )

            print("\nMost common segment transitions:")
            display(trans_counts.head(60))

            trans_counts.to_csv(
                os.path.join(OUT_DIR, f"{label_col}_segment_transition_counts.csv"),
                index=False
            )

Detected GROUP_COL: group
Detected TIME_COL: window_start

====================================================================================================
SEGMENT SEQUENCES FOR: rq3_process_label
====================================================================================================
group 1: 213 windows -> 23 segments
  social_conversation -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> inspection -> social_conversation -> inspection -> social_conversation -> task_conversation -> object_handover -> task_conversation -> inspection -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> inspection -> object_handover -> building -> task_conversation -> building -> merging
group 2: 253 windows -> 31 segments
  task_conversation -> object_handover -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> object_handover -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> object_handover -> moving_transport -> inspection -> task_conversation -> inspection -> object_handover -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> building -> task_conversation -> building -> object_handover -> building
group 3: 199 windows -> 39 segments
  social_conversation -> inspection -> task_conversation -> moving_transport -> task_conversation -> moving_transport -> inspection -> moving_transport -> task_conversation -> object_handover -> task_conversation -> object_handover -> task_conversation -> object_handover -> task_conversation -> object_handover -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> building -> moving_transport -> merging -> task_conversation -> building -> task_conversation -> object_handover -> building -> task_conversation -> moving_transport
group 5: 270 windows -> 23 segments
  task_conversation -> object_handover -> task_conversation -> object_handover -> task_conversation -> object_handover -> task_conversation -> object_handover -> inspection -> building -> task_conversation -> building -> inspection -> building -> task_conversation -> building -> task_conversation -> building -> task_conversation -> moving_transport -> task_conversation -> moving_transport -> merging
group 6: 152 windows -> 19 segments
  object_handover -> task_conversation -> social_conversation -> object_handover -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> building -> task_conversation -> building -> task_conversation -> building -> merging -> inspection -> moving_transport
group 7: 328 windows -> 37 segments
  social_conversation -> task_conversation -> social_conversation -> task_conversation -> object_handover -> social_conversation -> object_handover -> inspection -> task_conversation -> building -> social_conversation -> task_conversation -> object_handover -> building -> task_conversation -> building -> task_conversation -> building -> task_conversation -> building -> social_conversation -> building -> object_handover -> building -> task_conversation -> building -> task_conversation -> building -> task_conversation -> building -> moving_transport -> building -> moving_transport -> task_conversation -> object_handover -> moving_transport -> merging
group 8: 241 windows -> 52 segments
  social_conversation -> moving_transport -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> inspection -> task_conversation -> inspection -> moving_transport -> inspection -> task_conversation -> inspection -> task_conversation -> social_conversation -> task_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> inspection -> building -> task_conversation -> inspection -> task_conversation -> inspection -> object_handover -> task_conversation -> building -> object_handover -> building -> social_conversation -> task_conversation -> building -> task_conversation -> moving_transport -> inspection -> building -> social_conversation -> task_conversation -> moving_transport -> task_conversation -> moving_transport -> merging -> moving_transport -> merging -> task_conversation -> social_conversation
group 9: 351 windows -> 49 segments
  task_conversation -> building -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> inspection -> task_conversation -> social_conversation -> inspection -> building -> task_conversation -> inspection -> task_conversation -> building -> social_conversation -> inspection -> task_conversation -> inspection -> task_conversation -> social_conversation -> task_conversation -> social_conversation -> task_conversation -> building -> task_conversation -> social_conversation -> building -> social_conversation -> object_handover -> task_conversation -> inspection -> social_conversation -> inspection -> task_conversation -> inspection -> building -> inspection -> task_conversation -> building -> task_conversation -> building -> task_conversation -> building -> merging -> moving_transport -> task_conversation -> moving_transport -> merging
group 10: 73 windows -> 11 segments
  task_conversation -> object_handover -> task_conversation -> object_handover -> building -> task_conversation -> building -> moving_transport -> merging -> moving_transport -> merging

Segment count summary:
count     9.000000
mean     31.555556
std      13.848385
min      11.000000
25%      23.000000
50%      31.000000
75%      39.000000
max      52.000000
dtype: float64

Most common segment transitions:

                   from                   to  count
10           inspection    task_conversation     29
30    task_conversation           inspection     28
29    task_conversation             building     26
5              building    task_conversation     23
28  social_conversation    task_conversation     21
33    task_conversation  social_conversation     19
32    task_conversation      object_handover     18
23      object_handover    task_conversation     15
31    task_conversation     moving_transport      9
16     moving_transport              merging      8
6            inspection             building      7
25  social_conversation           inspection      7
19      object_handover             building      7
4              building  social_conversation      7
18     moving_transport    task_conversation      6
15     moving_transport           inspection      4
2              building     moving_transport      4
1              building              merging      3
12              merging     moving_transport      3
3              building      object_handover      3
27  social_conversation      object_handover      3
20      object_handover           inspection      3
8            inspection      object_handover      3
7            inspection     moving_transport      3
9            inspection  social_conversation      3
0              building           inspection      2
21      object_handover     moving_transport      2
24  social_conversation             building      2
13              merging    task_conversation      2
11              merging           inspection      1
17     moving_transport  social_conversation      1
14     moving_transport             building      1
22      object_handover  social_conversation      1
26  social_conversation     moving_transport      1

====================================================================================================
SEGMENT SEQUENCES FOR: rq3_compact_process_label
====================================================================================================
group 1: 213 windows -> 14 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> building -> merging
group 2: 253 windows -> 27 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> building -> preparation_or_transition -> building
group 3: 199 windows -> 37 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> building -> preparation_or_transition -> merging -> conversation -> building -> conversation -> preparation_or_transition -> building -> conversation -> preparation_or_transition
group 5: 270 windows -> 22 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> building -> preparation_or_transition -> building -> conversation -> building -> conversation -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> merging
group 6: 152 windows -> 11 segments
  preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> building -> conversation -> building -> conversation -> building -> merging -> preparation_or_transition
group 7: 328 windows -> 31 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> building -> conversation -> preparation_or_transition -> building -> conversation -> building -> conversation -> building -> conversation -> building -> conversation -> building -> preparation_or_transition -> building -> conversation -> building -> conversation -> building -> conversation -> building -> preparation_or_transition -> building -> preparation_or_transition -> conversation -> preparation_or_transition -> merging
group 8: 241 windows -> 36 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> building -> preparation_or_transition -> building -> conversation -> building -> conversation -> preparation_or_transition -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> merging -> preparation_or_transition -> merging -> conversation
group 9: 351 windows -> 40 segments
  conversation -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> preparation_or_transition -> conversation -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> building -> conversation -> building -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> preparation_or_transition -> conversation -> building -> conversation -> building -> conversation -> building -> merging -> preparation_or_transition -> conversation -> preparation_or_transition -> merging
group 10: 73 windows -> 11 segments
  conversation -> preparation_or_transition -> conversation -> preparation_or_transition -> building -> conversation -> building -> preparation_or_transition -> merging -> preparation_or_transition -> merging

Segment count summary:
count     9.000000
mean     25.444444
std      11.457651
min      11.000000
25%      14.000000
50%      27.000000
75%      36.000000
max      40.000000
dtype: float64

Most common segment transitions:

                        from                         to  count
4               conversation  preparation_or_transition     66
8  preparation_or_transition               conversation     55
0                   building               conversation     30
3               conversation                   building     28
7  preparation_or_transition                   building     15
2                   building  preparation_or_transition      9
9  preparation_or_transition                    merging      8
6                    merging  preparation_or_transition      4
1                   building                    merging      3
5                    merging               conversation      2

In [10]:

# ================================================================
# CELL 9 - RARE LABEL CHECK AND FINAL LABEL CHOICE
# ================================================================

# Recommended first:
# rq3_compact_process_label = safer for HMM because it has fewer states.
# rq3_process_label = more detailed, but may have sparse states.

SELECTED_RQ3_LABEL_COL = "rq3_compact_process_label"
# SELECTED_RQ3_LABEL_COL = "rq3_process_label"

MIN_LABEL_WINDOWS = 20

counts = df[SELECTED_RQ3_LABEL_COL].value_counts()
rare = set(counts[counts < MIN_LABEL_WINDOWS].index)

df["rq3_final_label"] = df[SELECTED_RQ3_LABEL_COL].where(
    ~df[SELECTED_RQ3_LABEL_COL].isin(rare),
    "other"
)

print("Selected label column:", SELECTED_RQ3_LABEL_COL)
print("MIN_LABEL_WINDOWS:", MIN_LABEL_WINDOWS)
print("Rare labels merged to other:", sorted(rare))

print("\nFinal RQ3 label distribution:")
display(df["rq3_final_label"].value_counts().reset_index().rename(
    columns={"index": "rq3_final_label", "rq3_final_label": "count"}
))

print("\nFinal labels:")
print(sorted(df["rq3_final_label"].unique()))

Selected label column: rq3_compact_process_label
MIN_LABEL_WINDOWS: 20
Rare labels merged to other: []

Final RQ3 label distribution:

                       count  count
0                   building   1051
1               conversation    485
2  preparation_or_transition    285
3                    merging    259

Final labels:
['building', 'conversation', 'merging', 'preparation_or_transition']

In [11]:

# ================================================================
# CELL 10 - SAVE NORMALIZED LABEL FILES
# ================================================================

normalized_path = os.path.join(OUT_DIR, "rq3_normalized_labels_full.csv")
df.to_csv(normalized_path, index=False)

print("Saved full normalized file:")
print(normalized_path)

keep_cols = []

for c in [GROUP_COL, TIME_COL, MAIN_LABEL_COL]:
    if c is not None and c in df.columns and c not in keep_cols:
        keep_cols.append(c)

for c in [
    "raw_label",
    "rq3_process_label",
    "rq3_compact_process_label",
    "rq3_conversation_binary",
    "rq3_final_label",
]:
    if c in df.columns and c not in keep_cols:
        keep_cols.append(c)

compact_path = os.path.join(OUT_DIR, "rq3_normalized_labels_compact.csv")
df[keep_cols].to_csv(compact_path, index=False)

print("\nSaved compact normalized file:")
print(compact_path)

metadata = {
    "main_file": MAIN_FILE,
    "main_label_col": MAIN_LABEL_COL,
    "group_col": GROUP_COL,
    "time_col": TIME_COL,
    "selected_rq3_label_col": SELECTED_RQ3_LABEL_COL,
    "final_label_col": "rq3_final_label",
    "out_dir": OUT_DIR,
}

metadata_path = os.path.join(OUT_DIR, "rq3_label_normalization_metadata.json")
with open(metadata_path, "w") as f:
    json.dump(metadata, f, indent=2)

print("\nSaved metadata:")
print(metadata_path)

print("\nDone.")

Saved full normalized file:
/content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/rq3_normalized_labels_full.csv

Saved compact normalized file:
/content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/rq3_normalized_labels_compact.csv

Saved metadata:
/content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/rq3_label_normalization_metadata.json

Done.


## How to use this output in the RQ3 / HMM notebook

Use:

```python
LABEL_FILE = "/content/drive/MyDrive/thesis/data/RQ3_LABEL_NORMALIZATION/rq3_normalized_labels_compact.csv"
LABEL_COL = "rq3_final_label"
```

Recommended:
- Start with `rq3_compact_process_label`, because it is safer for HMM/Markov models.
- Use `rq3_process_label` only if the detailed state counts and transition counts are sufficient.